name: Geeks on a Farm
markdown: redcarpet
pygments: true
paginate: 5
paginate_path: "blog/page:num"
baseurl: ""
speakers:
  - Florence Remy
  - Ralf Allrutz
  - Frank Manuel Saviane
  - Markus Schranner
  - Minna Janhonen
  - Tim Jaudszims
  - Guido Hegener
  - Willy Braun
  - Dan Toma
  - Leo Exter
  - Pascal Bastien
  - Klaus Haasis
  - Stephane Becker
